'use strict';
/**
 * Compiles src/frontend/cider/style.less (Cider's stylesheet, plus
 * launcher.less) to src/frontend/cider/cider.css, which the page loads.
 *
 *   node scripts/cider/build-css.js
 *
 * Cider compiles its LESS in the page at runtime with lib/less.js; the fork
 * commits the compiled CSS instead, so the page renders without a flash and
 * without fetching .less files. The compiler is the same vendored less.js,
 * run in Chromium (Playwright's, or CHROMIUM=/path/to/chrome), so there is no
 * new npm dependency. Rerun it after editing any .less file under cider/.
 */
const fs   = require('fs');
const path = require('path');
const { chromium } = require('@playwright/test');

const DIR = path.join(__dirname, '..', '..', 'src', 'frontend', 'cider');

// The .less imports inlined in place (less.js in a page would fetch them);
// .css imports are left for the browser, relative to cider.css
function inline(file) {
  const src = fs.readFileSync(path.join(DIR, file), 'utf8');
  return src.replace(/^@import url\("([^"]+\.less)"\);$/gm, (_, dep) => `/* ${dep} */\n${inline(dep)}`);
}

async function main() {
  const source = inline('style.less');
  const executablePath = process.env.CHROMIUM || process.env.E2E_CHROMIUM || undefined;
  const browser = await chromium.launch({ executablePath });
  try {
    const page = await browser.newPage();
    await page.addScriptTag({ path: path.join(DIR, 'lib', 'less.js') });
    const css = await page.evaluate(async (src) => (await globalThis.less.render(src, {})).css, source);
    const header = '/* Generated by scripts/cider/build-css.js from style.less; do not edit. '
      + 'Derived from Cider (github.com/ciderapp/Cider), AGPL-3.0: see LICENSE and NOTICE in this folder. */\n';
    fs.writeFileSync(path.join(DIR, 'cider.css'), `@charset "UTF-8";\n${header}${css.replace(/^@charset "UTF-8";\n/, '')}`);
    console.log(`cider.css: ${(css.length / 1024).toFixed(0)} KB`);
  } finally {
    await browser.close();
  }
}

main().catch((e) => { console.error(e); process.exit(1); });
